.TH IM\-CONFIG 8
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
im\-config \- set up input method framework configuration
.SH SYNOPSIS
.TP
.B im\-config [OPTION]

.SH OPTIONS
.TP 8
.B \-p
List all possible input method frameworks to STDOUT
even if any associated packages are not installed on the system.
.TP 8
.B \-i
List all installed input method frameworks to STDOUT.
.TP 8
.B \-d
List default values to STDOUT.
.TP 8
.B \-r
Report configuration values to STDOUT.
.TP 8
.B \-w
.I <input_method_name>

Wite the IM framework
.I <input_method_name>
.TP 8
.B \-c
Use console terminal dialog
.B \-q
Quiet logging
.TP 8
.B \-v
Verbose logging
.TP 8
.B \-t
.I <function_name>

Test execute
.I <function_name>
.TP 8
.B \-h
Print this message

This program is normally invoked without options.

Most of the options above are for debugging and self testing.

.SH "DESCRIPTION"
\fBim\-config\fP provides the framework to configure the input method framework
on X11 system (i.e., for original X Window).

.SH "TROUBLESHOOT"
If you have any problem, see the output of:

    journalctl -b -t im-config

If you experience problem around keyboard input, please file a bug report to
the im\-config package using reportbug(1) which automatically adds above
output.

You can disable \fBim\-config\fP as:

    im-config -n none

.SH "SEE ALSO"
.BR /usr/share/doc/im\-config/README.Debian
.SH AUTHOR
This manual page was written by Osamu Aoki <osamu@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
