#!/bin/sh -e
# check syntax of browser start script
echo "== DASH SYNTAX START =="
echo "Syntax check of installed dash script: im-config"
/bin/dash -n /usr/bin/im-config
echo "Syntax check of installed dash script: im-launch"
/bin/dash -n /usr/bin/im-launch
echo "Syntax check of installed dash script: 70im-config_launc"
/bin/dash -n /etc/X11/Xsession.d/70im-config_launch
echo "Syntax check of installed dash script: data/*.x11_env data/*.x11_launch"
for f in /usr/share/im-config/data/*.x11_env /usr/share/im-config/data/*.x11_launch; do
  /bin/dash -n "$f"
done
echo "== DASH SYNTAX SUCCESS =="
