#!/bin/sh -e
# UI test
# (C) 2026 Osamu Aoki <osamu@debian.org>, GPL-2+
#############################################################
# Parse command line arguments
#############################################################
IM_CONFIG_DIALOG=ZENITY
while [ -n "$1" ]; do
  case $1 in
    -z)
      IM_CONFIG_DIALOG=ZENITY
      ;;
    -k)
      IM_CONFIG_DIALOG=KDIALOG
      ;;
    -w)
      IM_CONFIG_DIALOG=WHIPTAIL
      ;;
    *)
      break
      ;;
  esac
  shift
done
export IM_CONFIG_DIALOG

im-config -t msgbox "Title (example)" "INFO TEXT\n2nd line\n3rd line"
echo
